### PR TITLE
Nft page uniques spec23

### PR DESCRIPTION
**Pull request by Douglasacost**
As of introducing Nodle's custom NFT pallet from Nodle's runtime spec 23, the queries for NFTs should go to substrateUniques where the previous storage of NFTs is relocated to.

### CODE REVIEW

**Comment by aliXsed** [comment]
@Douglasacost apart from some changes inside the .github folder which seems not related to this PR, it looks good. However this can break the proper query of NFTs for all the other chains. Can you find a neat way to limit this change to eden and paradis and only for the specs >= 23?

**Comment by Douglasacost** [comment]
> r this can break the proper query of NFTs for all the other chains. Can you find a neat way to limit this change to eden and paradis and only for the specs >= 23?

That's true. Will adapt it to only change the pallet on our chain

**Comment by Douglasacost** [comment]
@aliXsed I've applied some changes on a single file and change the api by spec version

**Comment by aliXsed** [comment]
@Douglasacost your latest solution is clever in terms of reducing the scope of change and limiting it to a single place. However it seems costly in terms of performance. If I have understood it correctly every time the useApi hook is used, we'd extract the `substrateUniques` sub records of `api.events` and `api.query `and attach them back as `uniques`.  This doesn't seem quite cheap especially that we do it regardless of the use of useApi. Adding to that useApi is called every 5 sec at least for ApiStatsCtx. I suggest we go for a solution where only the calls for api.events.uniques and api.query.uniques are replaced carefully only if substrateUniques exists or just for our chain spec > 23.

**Comment by Douglasacost** [comment]
> @Douglasacost your latest solution is clever in terms of reducing the scope of change and limiting it to a single place. However it seems costly in terms of performance. If I have understood it correctly every time the useApi hook is used, we'd extract the `substrateUniques` sub records of `api.events` and `api.query `and attach them back as `uniques`. This doesn't seem quite cheap especially that we do it regardless of the use of useApi. Adding to that useApi is called every 5 sec at least for ApiStatsCtx. I suggest we go for a solution where only the calls for api.events.uniques and api.query.uniques are replaced carefully only if substrateUniques exists or just for our chain spec >= 23.

Yes, that change was executing the override method each time a component dependant of `useApi` was rendered. It wasn't too costly despite it seems to be as the components and the API itself works like a subscription (looping)
Thanks to your comment I found a better place to make the override on the unique methods! We can override whatever we face in the future 👍

**Comment by Douglasacost** [comment]
we go in favor of: https://github.com/NodleCode/polkadot-js-apps/pull/34

**Pull request closed without merging**
