### PR TITLE
chore: update nodleprotocol to the latest release from polkadot-js-app v0.125.1

### PR DESCRIPTION
**Pull request by Douglasacost**

### CODE REVIEW

**Comment by Douglasacost** [comment]
@aliXsed this is the correct update for nodleprotocol.io, still being a huge one, this can be explained because they have added many auto-generated files, also many changes on the UI

**Review by ETeissonniere — APPROVED** [review]
Our own changes such as the CNAME, Github Actions, and endpoints are preserved. If you have tested the changes and you can successfully interact with our chain through this version then feel free to merge.

**Comment by Douglasacost** [comment]
Great!, I just need another approval 👍

**Comment by aliXsed** [comment]
@Douglasacost your last commit is not verified which if you have signed it, it means you need to add the public key of that signature to your Github account. 
I can force merge this one.

**Pull request merged**
